#!/bin/bash

APP_ANDROID_NAME=""
APP_ANDROID_VERSION=""
APP_ANDROID_BUILD_VERSION=""
APP_ANDROID_ID=""
APP_ANDROID_PACKAGE=""
APP_ANDROID_SCHEME=""
APP_ANDROID_ARTIFACT=""
APP_ANDROID_TAG_PREFIX=""

MONERO_COM="monero.com"
CAKEWALLET="cakewallet"
ONEKEY_XMR="onekey-xmr"
ONEKEY_ZEC="onekey-zec"
PWALLET="pwallet"

TYPES=($MONERO_COM $CAKEWALLET $ONEKEY_XMR $ONEKEY_ZEC $PWALLET)
APP_ANDROID_TYPE=$1

MONERO_COM_NAME="Monero.com"
MONERO_COM_VERSION="6.4.1"
MONERO_COM_BUILD_NUMBER=4165
MONERO_COM_BUNDLE_ID="com.monero.app"
MONERO_COM_PACKAGE="com.monero.app"
MONERO_COM_SCHEME="monero.com"

CAKEWALLET_NAME="Cake Wallet"
CAKEWALLET_VERSION="6.4.1"
CAKEWALLET_BUILD_NUMBER=4420
CAKEWALLET_BUNDLE_ID="com.cakewallet.cake_wallet"
CAKEWALLET_PACKAGE="com.cakewallet.cake_wallet"
CAKEWALLET_SCHEME="cakewallet"

ONEKEY_XMR_NAME="XMR Wallet"
ONEKEY_XMR_VERSION="1.2.1"
ONEKEY_XMR_BUILD_NUMBER=4
ONEKEY_XMR_BUNDLE_ID="com.yeats33.xmrwallet"
ONEKEY_XMR_PACKAGE="com.yeats33.xmrwallet"
ONEKEY_XMR_SCHEME="xmrwallet"
ONEKEY_XMR_ARTIFACT="xmr-wallet"
ONEKEY_XMR_TAG_PREFIX="xmr-v"

ONEKEY_ZEC_NAME="ZEC Wallet"
ONEKEY_ZEC_VERSION="0.1.0"
ONEKEY_ZEC_BUILD_NUMBER=1
ONEKEY_ZEC_BUNDLE_ID="com.yeats33.zecwallet"
ONEKEY_ZEC_PACKAGE="com.yeats33.zecwallet"
ONEKEY_ZEC_SCHEME="zecwallet"
ONEKEY_ZEC_ARTIFACT="zec-wallet"
ONEKEY_ZEC_TAG_PREFIX="zec-v"

PWALLET_NAME="PWallet"
PWALLET_VERSION="0.1.0"
PWALLET_BUILD_NUMBER=1
PWALLET_BUNDLE_ID="com.yeats33.pwallet"
PWALLET_PACKAGE="com.yeats33.pwallet"
PWALLET_SCHEME="pwallet"
PWALLET_ARTIFACT="pwallet"
PWALLET_TAG_PREFIX="pwallet-v"


if ! [[ " ${TYPES[*]} " =~ " ${APP_ANDROID_TYPE} " ]]; then
    echo "Wrong app type."
    return 1 2>/dev/null
    exit 1
fi

case $APP_ANDROID_TYPE in
	$MONERO_COM)
		APP_ANDROID_NAME=$MONERO_COM_NAME
		APP_ANDROID_VERSION=$MONERO_COM_VERSION
		APP_ANDROID_BUILD_NUMBER=$MONERO_COM_BUILD_NUMBER
		APP_ANDROID_BUNDLE_ID=$MONERO_COM_BUNDLE_ID
		APP_ANDROID_PACKAGE=$MONERO_COM_PACKAGE
		APP_ANDROID_SCHEME=$MONERO_COM_SCHEME
		;;
	$CAKEWALLET)
		APP_ANDROID_NAME=$CAKEWALLET_NAME
		APP_ANDROID_VERSION=$CAKEWALLET_VERSION
		APP_ANDROID_BUILD_NUMBER=$CAKEWALLET_BUILD_NUMBER
		APP_ANDROID_BUNDLE_ID=$CAKEWALLET_BUNDLE_ID
		APP_ANDROID_PACKAGE=$CAKEWALLET_PACKAGE
		APP_ANDROID_SCHEME=$CAKEWALLET_SCHEME
		;;
	$ONEKEY_XMR)
		APP_ANDROID_NAME=$ONEKEY_XMR_NAME
		APP_ANDROID_VERSION=$ONEKEY_XMR_VERSION
		APP_ANDROID_BUILD_NUMBER=$ONEKEY_XMR_BUILD_NUMBER
		APP_ANDROID_BUNDLE_ID=$ONEKEY_XMR_BUNDLE_ID
		APP_ANDROID_PACKAGE=$ONEKEY_XMR_PACKAGE
		APP_ANDROID_SCHEME=$ONEKEY_XMR_SCHEME
		APP_ANDROID_ARTIFACT=$ONEKEY_XMR_ARTIFACT
		APP_ANDROID_TAG_PREFIX=$ONEKEY_XMR_TAG_PREFIX
		;;
	$ONEKEY_ZEC)
		APP_ANDROID_NAME=$ONEKEY_ZEC_NAME
		APP_ANDROID_VERSION=$ONEKEY_ZEC_VERSION
		APP_ANDROID_BUILD_NUMBER=$ONEKEY_ZEC_BUILD_NUMBER
		APP_ANDROID_BUNDLE_ID=$ONEKEY_ZEC_BUNDLE_ID
		APP_ANDROID_PACKAGE=$ONEKEY_ZEC_PACKAGE
		APP_ANDROID_SCHEME=$ONEKEY_ZEC_SCHEME
		APP_ANDROID_ARTIFACT=$ONEKEY_ZEC_ARTIFACT
		APP_ANDROID_TAG_PREFIX=$ONEKEY_ZEC_TAG_PREFIX
		;;
	$PWALLET)
		APP_ANDROID_NAME=$PWALLET_NAME
		APP_ANDROID_VERSION=$PWALLET_VERSION
		APP_ANDROID_BUILD_NUMBER=$PWALLET_BUILD_NUMBER
		APP_ANDROID_BUNDLE_ID=$PWALLET_BUNDLE_ID
		APP_ANDROID_PACKAGE=$PWALLET_PACKAGE
		APP_ANDROID_SCHEME=$PWALLET_SCHEME
		APP_ANDROID_ARTIFACT=$PWALLET_ARTIFACT
		APP_ANDROID_TAG_PREFIX=$PWALLET_TAG_PREFIX
		;;
	$HAVEN)
		APP_ANDROID_NAME=$HAVEN_NAME
		APP_ANDROID_VERSION=$HAVEN_VERSION
		APP_ANDROID_BUILD_NUMBER=$HAVEN_BUILD_NUMBER
		APP_ANDROID_BUNDLE_ID=$HAVEN_BUNDLE_ID
		APP_ANDROID_PACKAGE=$HAVEN_PACKAGE
		;;
esac

export APP_ANDROID_TYPE
export APP_ANDROID_NAME
export APP_ANDROID_VERSION
export APP_ANDROID_BUILD_NUMBER
export APP_ANDROID_BUNDLE_ID
export APP_ANDROID_PACKAGE
export APP_ANDROID_SCHEME
export APP_ANDROID_ARTIFACT
export APP_ANDROID_TAG_PREFIX
