#!/usr/bin/env bash

APP_IOS_NAME=""
APP_IOS_VERSION=""
APP_IOS_BUILD_VERSION=""
APP_IOS_BUNDLE_ID=""
APP_IOS_SCHEME=""
APP_IOS_ARTIFACT=""
APP_IOS_TAG_PREFIX=""

MONERO_COM="monero.com"
CAKEWALLET="cakewallet"
ONEKEY_XMR="onekey-xmr"
ONEKEY_ZEC="onekey-zec"
PWALLET="pwallet"

TYPES=($MONERO_COM $CAKEWALLET $ONEKEY_XMR $ONEKEY_ZEC $PWALLET)
APP_IOS_TYPE=$1

MONERO_COM_NAME="Monero.com"
MONERO_COM_VERSION="6.4.1"
MONERO_COM_BUILD_NUMBER=171
MONERO_COM_BUNDLE_ID="com.cakewallet.monero"

CAKEWALLET_NAME="Cake Wallet"
CAKEWALLET_VERSION="6.4.1"
CAKEWALLET_BUILD_NUMBER=434
CAKEWALLET_BUNDLE_ID="com.fotolockr.cakewallet"

ONEKEY_XMR_NAME="XMR Wallet"
ONEKEY_XMR_VERSION="1.3.0"
ONEKEY_XMR_BUILD_NUMBER=5
ONEKEY_XMR_BUNDLE_ID="com.yeats33.xmrwallet"
ONEKEY_XMR_SCHEME="xmrwallet"
ONEKEY_XMR_ARTIFACT="xmr-wallet"
ONEKEY_XMR_TAG_PREFIX="xmr-v"

ONEKEY_ZEC_NAME="ZEC Wallet"
ONEKEY_ZEC_VERSION="1.3.0"
ONEKEY_ZEC_BUILD_NUMBER=2
ONEKEY_ZEC_BUNDLE_ID="com.yeats33.zecwallet"
ONEKEY_ZEC_SCHEME="zecwallet"
ONEKEY_ZEC_ARTIFACT="zec-wallet"
ONEKEY_ZEC_TAG_PREFIX="zec-v"

PWALLET_NAME="PWallet"
PWALLET_VERSION="1.3.0"
PWALLET_BUILD_NUMBER=2
PWALLET_BUNDLE_ID="com.yeats33.pwallet"
PWALLET_SCHEME="pwallet"
PWALLET_ARTIFACT="pwallet"
PWALLET_TAG_PREFIX="pwallet-v"


if ! [[ " ${TYPES[*]} " =~ " ${APP_IOS_TYPE} " ]]; then
    echo "Wrong app type."
    exit 1
fi

case $APP_IOS_TYPE in
	$MONERO_COM)
		APP_IOS_NAME=$MONERO_COM_NAME
		APP_IOS_VERSION=$MONERO_COM_VERSION
		APP_IOS_BUILD_NUMBER=$MONERO_COM_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$MONERO_COM_BUNDLE_ID
		;;
	$CAKEWALLET)
		APP_IOS_NAME=$CAKEWALLET_NAME
		APP_IOS_VERSION=$CAKEWALLET_VERSION
		APP_IOS_BUILD_NUMBER=$CAKEWALLET_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$CAKEWALLET_BUNDLE_ID
		;;
	$ONEKEY_XMR)
		APP_IOS_NAME=$ONEKEY_XMR_NAME
		APP_IOS_VERSION=$ONEKEY_XMR_VERSION
		APP_IOS_BUILD_NUMBER=$ONEKEY_XMR_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$ONEKEY_XMR_BUNDLE_ID
		APP_IOS_SCHEME=$ONEKEY_XMR_SCHEME
		APP_IOS_ARTIFACT=$ONEKEY_XMR_ARTIFACT
		APP_IOS_TAG_PREFIX=$ONEKEY_XMR_TAG_PREFIX
		;;
	$ONEKEY_ZEC)
		APP_IOS_NAME=$ONEKEY_ZEC_NAME
		APP_IOS_VERSION=$ONEKEY_ZEC_VERSION
		APP_IOS_BUILD_NUMBER=$ONEKEY_ZEC_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$ONEKEY_ZEC_BUNDLE_ID
		APP_IOS_SCHEME=$ONEKEY_ZEC_SCHEME
		APP_IOS_ARTIFACT=$ONEKEY_ZEC_ARTIFACT
		APP_IOS_TAG_PREFIX=$ONEKEY_ZEC_TAG_PREFIX
		;;
	$PWALLET)
		APP_IOS_NAME=$PWALLET_NAME
		APP_IOS_VERSION=$PWALLET_VERSION
		APP_IOS_BUILD_NUMBER=$PWALLET_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$PWALLET_BUNDLE_ID
		APP_IOS_SCHEME=$PWALLET_SCHEME
		APP_IOS_ARTIFACT=$PWALLET_ARTIFACT
		APP_IOS_TAG_PREFIX=$PWALLET_TAG_PREFIX
		;;
	$HAVEN)
		APP_IOS_NAME=$HAVEN_NAME
		APP_IOS_VERSION=$HAVEN_VERSION
		APP_IOS_BUILD_NUMBER=$HAVEN_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$HAVEN_BUNDLE_ID
		;;
esac

export APP_IOS_TYPE
export APP_IOS_NAME
export APP_IOS_VERSION
export APP_IOS_BUILD_NUMBER
export APP_IOS_BUNDLE_ID
export APP_IOS_SCHEME
export APP_IOS_ARTIFACT
export APP_IOS_TAG_PREFIX
